spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      indent_output: false

server:
  port: ${PORT:8080}

logging:
  level:
    root: info

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
